---
abstract: 'Async API for Elasticsearch using Promises'
author:
  - 'Clinton Gormley <drtech@cpan.org>'
build_requires:
  AE: '0'
  Cpanel::JSON::XS: '0'
  Data::Dumper: '0'
  EV: '0'
  File::Temp: '0'
  JSON::PP: '0'
  JSON::XS: '0'
  Log::Any::Adapter: '0'
  Log::Any::Adapter::Callback: '0'
  POSIX: '0'
  Test::Deep: '0'
  Test::Exception: '0'
  Test::More: '0.98'
  lib: '0'
  strict: '0'
  warnings: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.140640'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Search-Elasticsearch-Async
recommends:
  URI::Escape::XS: '0'
requires:
  AnyEvent::HTTP: '0'
  AnyEvent::TLS: '0'
  Moo: '1.003'
  Moo::Role: '0'
  Promises: '0.93'
  Scalar::Util: '0'
  Search::Elasticsearch: '1.13'
  Sub::Exporter: '0'
  Time::HiRes: '0'
  Try::Tiny: '0'
  namespace::clean: '0'
resources:
  bugtracker: https://github.com/elasticsearch/elasticsearch-perl/issues
  repository: git://github.com/elasticsearch/elasticsearch-perl.git
version: '1.15'
